name: Unit tests

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    strategy:      
      matrix:
        php: ['8.0', '8.1', '8.2', '8.3', '8.4']
        phpunit: ['10.0', '11.0']
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        extensions: mbstring, intl, json, mongodb
        coverage: pcov
    
    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Declare required PHPUnit version
      run: |
        composer require --no-update --dev phpunit/phpunit ^${{ matrix.phpunit }}

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    #- name: Run type checker
    #  run: ./vendor/bin/psalm
      
    - name: Run unit tests
      run: ./vendor/bin/phpunit --testdox
